### ISSUE TITLE
Research Vue

### ISSUE THREAD

**Issue by npdarrington** [the-bone-yard/frontend#4]
Our decision to use Vue for the FE will require doing additional research to understand Vue. This can be a thread to show all of the videos that we have can compile and share between others.

**Comment by npdarrington** [comment]
[A video for linking Typescript and Vue](https://vuejs.org/v2/guide/typescript.html)

**Comment by npdarrington** [comment]
[A video from freecodecamp.org for learning vue](https://www.youtube.com/watch?v=4deVCNJq3qc)

**Comment by npdarrington** [comment]
[A typescript video that I used to learn the fundamentals of Typescript](https://www.youtube.com/watch?v=BwuLxPH8IDs&t=7870s)

**Comment by bretm9** [comment]
[Vue Typescript Politico VueConf](https://www.youtube.com/watch?v=barrBizAqt0&t=261s&ab_channel=VueMastery)
