### ISSUE TITLE
Research Typescript

### ISSUE THREAD

**Issue by npdarrington** [the-bone-yard/frontend#8]
As we have decided to use Typescript for an additional technology in addition to Vue, here is a thread that we can use to start learning Typescript.

**Comment by npdarrington** [comment]
[A typescript video that I used to learn the fundamentals of Typescript](https://www.youtube.com/watch?v=BwuLxPH8IDs&t=7870s)

**Comment by bretm9** [comment]
[Hour long basic typescript tutorial](https://www.youtube.com/watch?v=NjN00cM18Z4&ab_channel=ProgrammingwithMosh)
